### ISSUE TITLE
Project implement 정리(README 용)

### ISSUE THREAD

**Issue by mike2ox** [KIST-Iceberg/Iceberg#24]
# SUMMARY

## 0. About Iceberg Challenge
**Statoil/C-CORE Iceberg Classifier Challenge**
[Ship or iceberg, can you decide from space?](https://www.kaggle.com/c/statoil-iceberg-classifier-challenge)

## 1. Development environment
OS : Linux 4.4.0-109-generic x86_64
GPU : NVIDIA TITAN Xp
CPU : Intel(R) core(TM) i7-7700K @ 4.20GHz
Tool : Tensorflow(Main), keras by python3

##### Filter
- High-pass Filtering 
- Lee(Speckle) Filter
- cor-diff filter (user custom)
##### Feature Scaling
- ~Decibel to Linear~
##### Correction
- Gamma Correction
##### Third Channel
- Combine([HH]*[HV]) 
- (HH + HV) / 2 
- -HH + -HV 
##### Transform
- ~Flip-Flop~
- Rotation (30 degree)

### 2) Deep Learning(Neural Nets)
- ~Super Resolution~
## 3. Important point
> ***모델마다 다른 결과를 낼 수 있음으로 종합적인 결론을 내는것은 불가능***
- Activation Function에서 ReLU보다 ELU, LeakyReLU 등이 더 좋은 결과 도출 예상
 :arrow_right: 예상과 달리 **ReLU가 여전히 좋은 결과**를 출력 #4 #5 
- Learning rate를 학습하면서 변화([cyclical LR](https://github.com/bckenstler/CLR), [Exponential decay](https://www.tensorflow.org/versions/r0.12/api_docs/python/train/decaying_the_learning_rate))시키면 더 좋은 결과 도출 예상
 :arrow_right: **fixed num(0.001)가 더 좋은 결과**를 출력 #5 

## 4. References
-

**Comment by kairos03** [comment]
https://github.com/KIST-Iceberg/Iceberg/wiki/SUMMARY
@quisutdeus7  이쪽 이용하는것이 좋을듯
