### ISSUE TITLE
Wiki image

### ISSUE THREAD

**Issue by kairos03** [KIST-Iceberg/Iceberg#27]
![channel-wise](https://user-images.githubusercontent.com/6357456/35053146-a357f13e-fba9-11e7-9e7c-ec4f6ae85283.png)

**Comment by kairos03** [comment]
[output.pdf](https://github.com/KIST-Iceberg/Iceberg/files/1655601/output.pdf)

**Comment by mike2ox** [comment]
[Tech Report.pdf](https://github.com/KIST-Iceberg/Iceberg/files/1656285/Tech.Report.pdf)
