### ISSUE TITLE
Image Preprocessing

### ISSUE THREAD

**Issue by dalbom** [KIST-Iceberg/Iceberg#7]
## Raw Input Data

![img_bands](https://user-images.githubusercontent.com/22551761/33949581-4d435cc4-e02a-11e7-9601-19f94de1b338.png)

Combined 채널은 |Band 1| * |Band 2| 로 계산

## Decibel to Linear

![img_linear](https://user-images.githubusercontent.com/22551761/33949638-75c0cc22-e02a-11e7-84cd-3e9ed981f79a.png)

## High-pass Filtering + Gamma Correction

![img_high](https://user-images.githubusercontent.com/22551761/33949654-81ad7864-e02a-11e7-97ae-82a36637c904.png)

**Comment by dalbom** [comment]
Rotation for data augmentation
![figure_1](https://user-images.githubusercontent.com/22551761/34203523-c06f7858-e57b-11e7-83eb-57a4d39ea8dd.png)

**Comment by kairos03** [comment]
17.12.30 현재 1등이 사용중인 필터는 아래로 추정됨
https://www.kaggle.com/jgroff/despeckling-synthetic-aperture-radar-sar-images

**Comment by kairos03** [comment]
Image Argumentation 을 통해 트레이닝 셋을 늘리는게 중요한것으로 보임 지속적인 토론이 일어나고 있음

**Comment by kairos03** [comment]
세부 진행은 `image preprocessing` 라벨을 통해 새로운 이슈를 만들어서 진행

**Comment by kairos03** [comment]
#9 에서 만든 데이터셋이 충분해 보임
이후 진행은 필터 변경 등을 추가

**Comment by kairos03** [comment]
http://elib.dlr.de/99079/2/2016_BENTES_Frost_Velotto_Tings_EUSAR_FP.pdf
@quisutdeus7
